version: '3'

services:
  backend: 
    build: .
    container_name: backend
    restart: unless-stopped
    environment: 
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET: ${SECRET}
    volumes:
      - "./src:/app/src"
    ports:
      - "3001:3001"
    networks:
      - bridge

  postgres:
    image: postgres:12-alpine
    volumes: 
      - ./postgres:/var/lib/postgresql/data/
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: postgres
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
